name: Build My AI APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Vosk English model
        run: |
          wget https://alphacephei.com/vosk/models/vosk-model-small-en-in-0.4.zip
          unzip vosk-model-small-en-in-0.4.zip
          mv vosk-model-small-en-in-0.4 model

      - name: Build APK with Buildozer Docker
        run: |
          docker pull kivy/buildozer:latest

          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyAI-APK
          path: bin/*.apk